"""workflow fields

Revision ID: 14aed272f8ba
Revises: 001
Create Date: 2026-07-26 00:03:06.461543

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14aed272f8ba'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alerts', sa.Column('assignment_notes', sa.String(), nullable=True))
    op.add_column('alerts', sa.Column('resolution_type', sa.String(), nullable=True))
    op.add_column('alerts', sa.Column('false_positive_reason', sa.String(), nullable=True))
    op.add_column('incidents', sa.Column('category', sa.String(), nullable=True))
    op.add_column('incidents', sa.Column('tags', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('incidents', 'tags')
    op.drop_column('incidents', 'category')
    op.drop_column('alerts', 'false_positive_reason')
    op.drop_column('alerts', 'resolution_type')
    op.drop_column('alerts', 'assignment_notes')
    # ### end Alembic commands ###
